"""baseline application schema

Revision ID: 09c4a8b3721a
Revises:
Create Date: 2026-07-06 10:14:14.508354
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '09c4a8b3721a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_provider_status',
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('provider')
    )
    op.create_table('news_raw',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('published_utc', sa.String(length=80), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('news_raw', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_raw_fingerprint'), ['fingerprint'], unique=True)
        batch_op.create_index(batch_op.f('ix_news_raw_provider'), ['provider'], unique=False)

    op.create_table('signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_key', sa.String(length=64), nullable=False),
    sa.Column('ticker', sa.String(length=30), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('event_score', sa.Float(), nullable=False),
    sa.Column('market_reaction_score', sa.Float(), nullable=False),
    sa.Column('signal', sa.String(length=10), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('data_source', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_key', 'ticker', 'trade_date', name='uq_signal_event_ticker_date')
    )
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signals_event_key'), ['event_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_ticker'), ['ticker'], unique=False)

    op.create_table('stock_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=30), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('return_1d', sa.Float(), nullable=True),
    sa.Column('return_3d', sa.Float(), nullable=True),
    sa.Column('return_5d', sa.Float(), nullable=True),
    sa.Column('volume_ratio', sa.Float(), nullable=True),
    sa.Column('volatility_5d', sa.Float(), nullable=True),
    sa.Column('volatility_ratio', sa.Float(), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('data_source', sa.String(length=30), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'trade_date', name='uq_stock_price_ticker_trade_date')
    )
    with op.batch_alter_table('stock_prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_prices_ticker'), ['ticker'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_prices_trade_date'), ['trade_date'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('profile_image_url', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=30), nullable=False),
    sa.Column('alert_channel', sa.String(length=80), nullable=False),
    sa.Column('channel_connected', sa.Boolean(), nullable=False),
    sa.Column('interests', sa.JSON(), nullable=False),
    sa.Column('alert_settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_user_provider_identity')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_provider_user_id'), ['provider_user_id'], unique=False)

    op.create_table('alert_history',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('trigger', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('tone', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_history_user_id'), ['user_id'], unique=False)

    op.create_table('kakao_alert_rules',
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.Column('rule_id', sa.String(length=80), nullable=False),
    sa.Column('icon', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'rule_id')
    )
    op.create_table('news_filtered',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('raw_id', sa.Integer(), nullable=False),
    sa.Column('source_score', sa.Float(), nullable=False),
    sa.Column('keyword_score', sa.Integer(), nullable=False),
    sa.Column('duplicate_flag', sa.Boolean(), nullable=False),
    sa.Column('content_length', sa.Integer(), nullable=False),
    sa.Column('passed_filter', sa.Boolean(), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.Column('filtered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['raw_id'], ['news_raw.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('news_filtered', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_filtered_raw_id'), ['raw_id'], unique=True)

    op.create_table('portfolio_assets',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.Column('asset_name', sa.String(length=120), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('market', sa.String(length=20), nullable=False),
    sa.Column('industry', sa.String(length=80), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('average_buy_price', sa.Float(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('recent_sell_price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('decision_memo', sa.Text(), nullable=True),
    sa.Column('related_news_count', sa.Integer(), nullable=False),
    sa.Column('caution_news_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'symbol', 'market', name='uq_portfolio_user_symbol_market')
    )
    with op.batch_alter_table('portfolio_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_assets_user_id'), ['user_id'], unique=False)

    op.create_table('user_preferences',
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.Column('interested_markets', sa.JSON(), nullable=False),
    sa.Column('interested_industries', sa.JSON(), nullable=False),
    sa.Column('alert_enabled', sa.Boolean(), nullable=False),
    sa.Column('notification_channels', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_settings',
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    op.drop_table('user_preferences')
    with op.batch_alter_table('portfolio_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_assets_user_id'))

    op.drop_table('portfolio_assets')
    with op.batch_alter_table('news_filtered', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_filtered_raw_id'))

    op.drop_table('news_filtered')
    op.drop_table('kakao_alert_rules')
    with op.batch_alter_table('alert_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_history_user_id'))

    op.drop_table('alert_history')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_provider_user_id'))
        batch_op.drop_index(batch_op.f('ix_users_provider'))

    op.drop_table('users')
    with op.batch_alter_table('stock_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_prices_trade_date'))
        batch_op.drop_index(batch_op.f('ix_stock_prices_ticker'))

    op.drop_table('stock_prices')
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signals_ticker'))
        batch_op.drop_index(batch_op.f('ix_signals_event_key'))

    op.drop_table('signals')
    with op.batch_alter_table('news_raw', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_raw_provider'))
        batch_op.drop_index(batch_op.f('ix_news_raw_fingerprint'))

    op.drop_table('news_raw')
    op.drop_table('data_provider_status')
    # ### end Alembic commands ###
